[phases.setup]
nixPkgs = ["python311", "chromium", "chromedriver", "ffmpeg"]

[phases.install]
cmds = [
  "python -m venv.venv",
  "..venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "..venv/bin/activate && python bot.py"
