services:
  - type: worker
    name: orangecarrier-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: "apt-get update && apt-get install -y chromium-driver ffmpeg && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: starter
    autoDeploy: true
